[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }

[versions]
kotlin = "2.0.21"
agp = "8.7.2"
core-ktx = "1.13.1"
test-core = "1.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"
test-ext-junit = "1.2.1"
test-orchestrator = "1.5.1"
mockito-kotlin = "5.4.0"
mockito-android = "5.14.2"
espresso-core = "3.6.1"
appcompat = "1.7.0"
paparazzi = "1.3.4"
ktlint = "12.1.1"
detekt = "1.23.7"
constraintlayout = "1.1.0"
composeBom = "2024.11.00"
junit = "5.11.3"
junit4 = "4.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }

# UI
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
google-material = { module = "com.google.android.material:material", version = "1.12.0"}

#Instrument Test
compose-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
android-test-core = { group = "androidx.test", name = "core", version.ref = "test-core" }
android-test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
android-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
android-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core" }
android-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext-junit" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito-android" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "test-orchestrator" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit4" }

# JUnit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }

[bundles]
android-test = [ "android-test-core", "android-test-runner", "android-test-rules", "android-test-core-ktx", "android-test-ext-junit" ]
mockito = ["mockito-kotlin", "mockito-android"]
jupiter = ["junit-jupiter", "junit-jupiter-engine", "junit-jupiter-params"]
compose = ["compose-material", "compose-material3", "compose-ui-tooling-preview"]
