name: On Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  workflow_dispatch:

jobs:
  onPullRequestJob:
    env:
      ANDROID_HOME: ${{ github.workspace }}/bin/androidSdk
    name: Verify code base when pull request is published/updated
    runs-on: ubuntu-24.04
    steps:
      - name: Run pull request workflow
        uses: govuk-one-login/mobile-android-pipelines@5b2867aad9ac331b3cd8e619d51a980a8dfa8f22
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
