name: On Push Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump_version:
    env:
      JDK_VERSION: 17
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-24.04

    steps:
      - name: Run deployment workflow
        uses: govuk-one-login/mobile-android-pipelines@5b2867aad9ac331b3cd8e619d51a980a8dfa8f22
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
