name: On Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  workflow_dispatch:

jobs:
  onPullRequestJob:
    env:
      ANDROID_HOME: ${{ github.workspace }}/bin/androidSdk
    name: Verify code base when pull request is published/updated
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout codebase'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          fetch-tags: true

      - name: Clean workspace
        uses: ./mobile-android-pipelines/actions/clean-workspace

      - name: 'Detect architecture'
        id: detect-arch
        uses: ./mobile-android-pipelines/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./mobile-android-pipelines/actions/setup-runner

      - name: Verify Conventional commit standards against latest git tag
        run: cog check -l
        shell: bash

      - name: Build artefact for release
        run: |
          ./gradlew assemble
        shell: bash

#      - name: Increment the release version using Conventional Commits
#        id: versioning
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#
#          current_version=$(cog -v get-version)
#          echo "current_version=$current_version" >> $GITHUB_OUTPUT
#
#          cog bump --auto
#
#          new_version=$(cog -v get-version)
#          echo "new_version=$new_version" >> $GITHUB_OUTPUT
#        shell: bash

      - name: Publish the release
        run: |
          git push --follow-tags && git push --tags
        shell: bash

      - name: Publish package
        uses: ./mobile-android-pipelines/actions/maven-publish
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Run pull request workflow
        uses: govuk-one-login/mobile-android-pipelines@f8b699c11df39cfbf32c74468720989f023992f7
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
